import type { Metadata } from 'next'
import { poppins } from './lib/fonts'
import './globals.scss'

import { SectionProvider } from './context/SectionContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <SectionProvider>
      <html lang="en">
        <body className={poppins.className}>{children}</body>
      </html>
    </SectionProvider>
  )
}
